Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WorkTimer.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkTimer.Domain.Timers;
using Timer = WorkTimer.Domain.Timers.Timer;

namespace WorkTimer.Pages;

public class IndexModel : PageModel
{
    [BindProperty]
    public Timer Timer { get; set; }
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        Timer = new Timer();
    }

    public void OnPostSubmit()
    {
        Timer.MorningStart = TimeOnly.Parse(Request.Form["morning-start"]);
        Timer.MorningEnd = TimeOnly.Parse(Request.Form["morning-end"]);
        Timer.AfternoonStart = TimeOnly.Parse(Request.Form["afternoon-start"]);

        Timer.SetAfternoonEnd();
    }

    public void OnPostResetForm()
    {
        Timer = new Timer();
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "WorkTimer";
}

<div class="text-center">
    <h1 class="display-4">WorkTimer</h1>

    <form method="post">
        <div class="row justify-content-md-center py-2">
            <div class="col-sm-2">
                <label for="morning-start" class="form-label">Início</label>
            </div>
            <div class="col-auto">
                <input type="time" id="morning-start" name="morning-start" class="form-control" asp-for="Timer.MorningStart" required />
            </div>
        </div>

        <div class="row justify-content-md-center py-2">
            <div class="col-sm-2">
                <label for="morning-end" class="form-label">Almoço</label>
            </div>
            <div class="col-auto">
                <input type="time" name="morning-end" class="form-control" asp-for="Timer.MorningEnd" required />
            </div>
        </div>

        <div class="row justify-content-md-center py-2">
            <div class="col-sm-2">
                <label for="afternoon-start" class="form-label">Retorno</label>
            </div>
            <div class="col-auto">
                <input type="time" name="afternoon-start" class="form-control" asp-for="Timer.AfternoonStart" required />
            </div>
        </div>

        <div class="row justify-content-md-center py-2">
            <div class="col-sm-2">
                <label for="afternoon-end" class="form-label">Fim do expediente</label>
            </div>
            <div class="col-auto">
                <input type="time" name="afternoon-end" class="form-control" asp-for="Timer.AfternoonEnd" disabled />
            </div>
        </div>

        <div class="py-3 justify-content-md-center">
            <input type="submit" class="btn btn-primary" value="Calcular" asp-page-handler="Submit" />
            <input type="submit" class="btn btn-light" value="Limpar" asp-page-handler="ResetForm" />
        </div>
    </form>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkTimer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkTimer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WorkTimer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WorkTimer - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>